----------------------------------------------------------------------
-- ForeverClassesEnhanced — Lore Data
--
-- Brief lore descriptions for enhanced classes, sourced from
-- the Warcraft Wiki (warcraft.wiki.gg).
----------------------------------------------------------------------

FCE = FCE or {}

----------------------------------------------------------------------
-- Lore text per character
----------------------------------------------------------------------
FCE.LoreData = {

    ["Apothecary"] = "The Royal Apothecary Society is an alchemical society created by Lady Sylvanas Windrunner in order to create a new undead plague. As an Apothecary, you are constantly brewing up new plagues and poisons to destroy the Dark Lady's enemies. Your journey will culminate in unleashing a deadly concoction upon the human settlement of Southshore.",

    ["Beastmaster"] = "The Mok'Nathal Clan are half-ogre, half-orc hybrids. Because of their ancestry, they are seen as outcasts among orcish and ogre factions, and find comfort in commanding powerful wild beasts. Since the demise of the Mok'Nathal Clan, other races have adopted the tradition of the Beastmaster. As a Beastmaster, you seek to hunt and tame the most challenging game. Your journey will culminate in taming a Son of Hakkar in Zul'Gurub.",

    ["Prospector"] = "For untold centuries, Dwarves wandered the mountains of Khaz Modan searching for untapped veins of ore. With the discovery of their own titan origins and the founding of the Explorers' Guild, their wanderings have spread until they now cover all of Azeroth. As a Prospector, you wander in and under the mountains in search of fresh veins of ore. Your journey will culminate in smelting a precious ore near the Molten Core of Blackrock Mountain.",

    ["Bloodmage"] = "While High Elves were still members of the Alliance, some began to turn to the darkest parts of magic, embracing the fire and heat of what some people fear to be demonic magic. Many of these Bloodmages were raised as undead during the Lich King's invasion of Quel'Thalas, and have since joined the Forsaken. As an Undead Bloodmage, your journey will culminate in taking revenge from Arthas by defeating two Liches under his command.",

    ["Fletcher"] = "During the Troll Wars, Human marksmen fought alongside the High Elves of Quel'Thalas. Human artisans observed the bowyer techniques of the Farstriders and implemented them in their army and scouting units. As Stormwind industrialized, fletching shifted from a solitary forest craft to a vital military trade with engineers mass-producing iron arrowheads. Throughout your journey as a Fletcher, you will be tested on your ability to kite deadly enemies using your bow.",

    ["Elven Ranger"] = "In the wake of its war with the Burning Legion, High Priestess Tyrande Whisperwind led the Night Elves in rebuilding their ruined society. From the ranks of the Sisterhood of Elune, she forged the Sentinels, whose duty it was to protect their newly-emergent society. The Ranger division of the Sentinels are specialized in woodland warfare and possess minor druidic abilities expressed in their traps and poisons. Throughout your journey as an Elven Ranger, you will take on increasingly difficult missions and prove your worth to the Sisterhood.",

    ["Buccaneer"] = "Piracy is considered to be a vile crime in Azeroth, and those caught are sentenced to death by both the Alliance and the Horde. In some cases, pirates may obtain a pardon for past crimes if they manage to accomplish a mission of great importance, giving them access to a faction. As a Buccaneer, your journey begins with seeking a pardon.",

    ["Death Knight"] = "During the Third War, the Lich King Ner'zhul created a new breed of death knights: malevolent, rune-wielding warriors of the Scourge. These modern death knights were created mainly from human paladins who lost their faith and pledged themselves to the Lich King in exchange for immortality. As a Death Knight of Acherus, your journey will culminate in massacring soldiers of the Argent Dawn.",

    ["Dark Rider"] = "During the Second War, Gul'dan created an army of necrotic soldiers by placing the souls of dead Orc Warlocks from the Shadow Council inside the corpses of Human knights. Riding skeletal horses and wielding jeweled truncheons empowered with dark magic, these dark soldiers sowed chaos and fear throughout Azeroth. As a Dark Rider of the Old Horde, your journey will culminate in taking revenge from the Night Elves that defeated the Burning Legion in the Battle of Mount Hyjal.",

    ["Demon Hunter"] = "Ten thousand years ago, Illidan Stormrage was gifted demonic powers by Sargeras himself. After he conquered Outland, Illidan envisioned making warriors in his own image, fellow elves empowered by demonic energy, willing to sacrifice everything to destroy the Legion. In the following years, many Night Elves sought Illidan out to undergo Demon Hunter training. As a Demon Hunter, your journey will culminate in destroying the Shadow Council's stronghold in Felwood and defeating Razelikh the Defiler in Blasted Lands.",

    ["Druid of the Claw"] = "Wild Gods are primal manifestations of nature and are among the first living creatures to roam Azeroth. Many of them appear in the form of gargantuan animals; Ursoc, the Bear God, is one of these massive demigods. Among the Night Elves, the Druids of the Claw take on the form of bears and wander the wilderness on a never-ending pilgrimage dedicated to Ursoc. As a Druid of the Claw, you are a protector of nature and a master of your mighty bear form. Throughout your journey, you will fight against the Venture Company who seek to mine and exploit Azeroth's natural resources.",

    ["Earthcaller"] = "Primordial Azeroth was ruled by the four Elemental Lords (of Fire, Earth, Air, and Water) who constantly clashed with one another, keeping the world in a perpetual state of chaos over the ages. More recently, a neutral faction of shaman called 'The Earthen Ring' was established to preserve the balance between the elements. The organization aims to gather the most powerful shaman of Azeroth and recruited a number of Earthcallers. As an Earthcaller, you have mastery of elemental earth, the toughest and strongest of the elements. Throughout your journey, you will best increasingly challenging elemental spirits.",

    ["Exemplar"] = "Battlefields are bloody places, but they are also the proving grounds of heroes. Among the many legendary feats of bravery are the deeds of the Exemplars: men and women who hold their banners high and charge into battle, inspiring courage in those who ride beside them. They are living symbols of faith and justice, wearing their faction's tabards and colors as ordained protectors of their kings and queens. Throughout your journey as an Exemplar, you will take on increasingly difficult missions and prove your worth to the crown.",

    ["Deathguard"] = "The Forsaken are a faction of intelligent undead who broke away from the Scourge after the Third War. Under the command of Lady Sylvanas Windrunner, these free-willed undead took control of much of the ruins of Lordaeron, and founded their own kingdom. The Forsaken entered an alliance of convenience with the Horde. As a Forsaken military force mainly deployed across Lordaeron, the Deathguard do not interact with the other Horde races very often, and rarely speak Orcish. Throughout your journey as a Deathguard, you will take on increasingly difficult missions and prove your worth to the Dark Lady.",

    ["Techno-mage"] = "Tinkers are among the smartest of the adventurers setting out to explore and conquer Azeroth. The creators of incredible inventions, from crazy multipurpose knives to steam saws to discombobulators, their devices allow them to overcome nearly any situation — and if they don't have the device they need, they just might be able to design and create a new one on the spot. Techno-mages are tinkers who combine their use of technology with magical knowledge. As a Techno-mage, your journey will culminate in defeating Trade Master Kovic with his own mechanical companion.",

    ["Mountain King"] = "Dwarves are an ancient, bold, and courageous race descended from the Earthen. They spend their time refining metal and stone into powerful weapons and beautiful jewelry. However, when the call to battle sounds, they rise up to defend their allies with unmatched courage and valor. Mountain Kings, or Thanes as they are known in Khaz Modan, are the mightiest Dwarven warriors. Unconcerned with their race's preoccupation with mechanical devices and mining precious minerals, Mountain Kings live only for battle. As a Mountain King, your journey will culminate in rescuing King Magni's daughter, the Princess of Ironforge, from the evil Dark Iron Dwarves.",

    ["Mountaineer"] = "The typical Dwarven rifleman is a native of the Ironforge clan who specializes in use of the long rifle. Typically, they use their climbing skills to work their way into a good vantage point, then rain death upon their enemy from above. Many Dwarven riflemen take up the role of Mountaineers as protectors of the mountains of Khaz Modan. As skilled engineers, Mountaineers have long been renowned for the craftsmanship of their custom-built rifles. As a Mountaineer, your journey will culminate in rescuing King Magni's daughter, the Princess of Ironforge, from the evil Dark Iron Dwarves.",

    ["Necromancer"] = "Necromancy is considered to be a dark, corruptive energy, and is illegal in the Seven Kingdoms. In the Magocracy of Dalaran, researching into this banned field of magic was expressly forbidden by laws almost as old as the Kirin Tor itself. Those who persisted with the dark arts were censored, stripped of their power and influence, and banned from the kingdom. As an aspiring Necromancer, you hone your ability to drain life from the living but have yet to raise a corpse. By the end of your journey, you will successfully raise and control the dead.",

    ["Plagueshifter"] = "Few forces have devastated the world as badly as plague. The Plaguelands of Lordaeron are a testament to the ravages that disease can bring to the world. After long and careful deliberation, the Horde formed a new order of druids, the Plagueshifters, who were charged with reclaiming the Plaguelands and other stricken areas. Plagueshifters study the plague and other diseases to eradicate them wherever they fester. As a Plagueshifter, your journey will culminate in cleansing the polluted filth that Arthas brought to Stratholme.",

    ["Priestess of the Moon"] = "The Sisterhood of Elune are a religious order of Night Elf Priests dedicated to the worship and servitude of the moon goddess, Elune. While unknown for long, as an organization they have existed long before the Great Sundering, and worship of Elune among the Night Elves dates back about 15,000 years. Priestess of the Moones are the women who make up the Sisterhood. They ride the fearless frostsabers into battle and are masters of arcane magic. Throughout your journey as a Priestess of the Moon, you will take on increasingly difficult missions and prove your worth to the Sisterhood.",

    ["Farseer"] = "Before they were corrupted and manipulated by the Demon Lord Kil'jaeden, Orcs were a shamanistic people cultivating a primitive clan-based society. Farseers were the exceptionally wise shaman that play the role of advisors and took on leadership positions in their communities. As Thrall's New Horde try to return to their shamanistic traditions, Farseers have reappeared as highly esteemed and respected members of their factions. Your journey as a Farseer will culminate in defeating the Warchief of the Dark Horde, the largest threat to Thrall.",

    ["Huntress"] = "In the wake of its war with the Burning Legion, High Priestess Tyrande Whisperwind led the Night Elves in rebuilding their ruined society. From the ranks of the Sisterhood of Elune, she forged the Sentinels, whose duty it was to protect their newly-emergent society. The Huntress division of the Sentinels are strong and swift. They ride the feral nightsabers into battle. As a Huntress, your journey will culminate in liberating the hidden Night Elven city of Shen'dralar from its crazed ruler.",

    ["Druid of the Talon"] = "Before and during the Third War, almost all Druids were organized into different subgroups, each with its own totem animal — one of the most famous, and most influential in the Third War, were the Druids of the Talon. As Totemic Druids, Druids of the Talon base their magic solely off of the Owlkin, a serene, powerful creature, believed by the Night Elves and Tauren to have been created by the moon goddess Elune to protect her sacred places. As a Druid of the Talon, your journey will culminate in helping the Cenarion Circle to obtain a mighty staff.",

    ["Pyremaster"] = "Orcs burn their dead. In a world filled with magic, magic insinuates itself in ritual. Founded in the mysteries of certain cults on Draenor, the Pyremaster is the enactor of ritual. This funerary priest guides the dead through fire, through loss of flesh, so their naked spirits may conquer the elements; in order to protect his duties and his person, he commands both bone and fire. Throughout your journey as a Pyremaster, you will light fires under your fallen allies to cremate their corpses and honor their spirit.",

    ["Blademaster"] = "In Orc society, the Burning Blade Clan is known for applying a sticky, smelly, and highly flammable grease to their swords and axes before battle. These famous Burning Blade warriors are known as Blademasters. Though some choose to ignite the 'blazegrease' on their weapons before battle, most let the inevitable contact of blades and armor spark the grease for unpredictable intimidation. Your journey as a Blademaster will culminate in defeating the Warchief of the Dark Horde, the largest threat to Thrall.",

    ["Spirit Champion"] = "Some Shaman devote themselves to the warlike aspects inherent in their abilities. They still possess a modicum of magical ability, but train their bodies and reflexes to focus more on combat. By drawing on the anger of the spirits, an experienced Spirit Champion can strike their enemies dead instantly. Spirit Champions meditate especially before battle. They prefer quiet places of natural beauty, such as mountaintops and forest glades, but they can meditate anywhere as long as they are undisturbed. Your journey as a Spirit Champion will culminate in helping the Cenarion Circle to obtain a devastatingly mighty weapon.",

    ["Barbarian"] = "The Barbarian is a ferocious Warrior. He is uncivilized and brutal, relying on instincts, anger, and raw physical might instead of tactics or fancy swordsmanship. The terms 'barbarian' and 'barbaric' have been used in reference to many races considered cruel or primitive, including Orcs, Trolls, and early Humans. Throughout your journey as a Barbarian, you will take on increasingly difficult quests that require you to slay vast numbers of humanoids.",

    ["Savagekin"] = "The most primal of druids, Savagekin bear an ancient but obscure legacy. Whereas some druids seek to command nature or bond with it, the Savagekin surrenders himself to the natural world, abandoning much of their humanity to live with the beasts. As a Savagekin, you spend most of your time in animal form. As you shapeshift you gain strength and finesse, but come close to becoming irreversibly feral. Throughout your journey as a Savagekin, you will constantly battle the inner beasts that threatens to consume you, clinging to your last vestiges of sentience.",

    ["Shadow Hunter_PRIEST"] = "Shadow Hunters are reclusive and wily masters of voodoo and were once the highest authority amongst trolls and their respective warbands. Their spirit powers can both heal and curse, walking the line of dark and light in hope of saving the future of Trollkind, doing whatever it takes to secure a future for their kin. As a Shadow Hunter, you can feel the Loa channel through you when you wear your ceremonial rush'kah mask. Throughout your journey as a Shadow Hunter, you will take revenge from the Bloodscalp, Skullsplitter, and Gurubashi Trolls for pushing the Darkspear Tribe out of Stranglethorn Vale.",

    ["Shadow Hunter_HUNTER"] = "Roughly spoken, Shadow Hunters are former headhunters who have gone deeply into the arts of voodoo and Loa. However, they have not forgotten their hunting skills, which makes a Shadow Hunter very dangerous in combat. They can stand far away from their enemies while shooting magical arrows at rapid speed and track down enemies with ease. Throughout your journey as a Shadow Hunter, you will take revenge from the Bloodscalp, Skullsplitter, and Gurubashi Trolls for pushing the Darkspear Tribe out of Stranglethorn Vale.",

    ["Scarlet Champion"] = "The Scarlet Crusade is a fanatical religious sect dedicated to the eradication of the undead from Lordaeron. Similarly to the Argent Dawn, the Crusade evolved from the Order of the Silver Hand in the aftermath of the Third War. While the Argent Dawn maintained the Silver Hand's original compassionate ideals by welcoming all races to fight the Scourge neutrally, the Scarlet Crusade devolved into a fanatical, xenophobic cult manipulated by outside forces. Throughout your journey as a Scarlet Champion, you will start the question the twisted ethics of the cult you were raised in.",

    ["Spiritwalker"] = "Spiritwalkers are mystical Tauren casters who travel far and wide to find kindred spirits. They carry lanterns to light shadowed spirit paths. Believed to be the ill omen of a coming age, these Tauren are held in near reverence by their people in Kalimdor, often becoming reclusive shamans. Spiritwalkers maintain the balance between the world of the living and the spirit realm. They can travel into the memories of the dead to glean clues about the past. Throughout your journey as a Spiritwalker, you will explore all four corners of Azeroth.",

    ["Templar"] = "Templars are a type of religious combatants. They can be skilled in battle or invaluable as support units. They are also the most righteous in their demeanor. Strength of arms or purity of mind are strict requirements. Templars stop at nothing to fulfill their divine purpose of bringing justice and purging the wicked. They wield the Light and unleash devastating combinations of Physical or Holy attacks that vanquish their enemies. As a Templar, your journey will culminate in cleansing the Scourge from Stratholme and becoming Honored amongst the Argent Dawn.",

    ["Brewmaster"] = "Hailing from the secretive Pandaren Empire, the mighty Brewmasters are masters of crafting drinks and concoctions that grant special abilities to themselves and others. They are sturdy brawlers who may seem to struggle with balance as they chug their concoctions in the middle of a fight, but this unpredictable behavior is far from foolhardiness. While most are Pandaren, there are also Brewmasters among other races and factions. Throughout your journey as a Brewmaster, you will take on increasingly difficult tasks to acquire powerful flasks.",

    ["Spellblade"] = "Spellblades are spellcasters who accompany soldiers into the heart of battle. The generations of warfare on Azeroth have given Spellblades time to hone useful frost spells into simple and secret rituals, called battlemagics, which are passed from Spellblades to another. They can wield a sword in one hand, and a staff in the other. As Spellblades accompany warriors into battle, they become better at defending themselves than other wizards. Throughout your journey as a Spellblade, you will hone your ability to control and best big crowds of enemies.",

    ["Witch Doctor_SHAMAN"] = "Witch Doctors are spellcasters and alchemists. Troll witch doctors utilize voodoo and nature magic, while augmenting their abilities with juju, mojo, and muisek. Ancestral staves and rush'kah masks are used by Witch Doctors to call upon their ancestors and Loa. They are particularly skilled at all crafting and performing chants and dances. They often use the smoke of the herbs they collect to draw evil from its hiding places. As a Witch Doctor, your journey will culminate in performing a dark dance at the peak of Jintha'Alor while wearing cursed items.",

    ["Witch Doctor_PRIEST"] = "Some Witch Doctors feel a stronger calling from the deep, whispering shadows. They become solitary hermits, retreating to the fetid heart of murky swamps where the Loa of Death, Bwonsamdi, has a stronger presence. Their isolated domains serve not only as sanctuaries for forbidden rituals but also as prime sources for the rare, toxic herbs, venomous insects, and ancient bone fragments crucial for their powerful concoctions. Their isolation requires them to hone their survival, fishing, and cooking skills. As a Witch Doctor, your journey will culminate in performing a dark dance at the peak of Jintha'Alor while wearing cursed items.",

    ["Runemaster"] = "The traditions of the Runemasters date back to the ancient time of the Titans, creators of runic magic and the imprisoners of Old Gods. Their creation, the Dwarves, quickly mastered the mysteries of the runes taught to them. Others races discovered the power of runes independently by studying Azeroth's ley lines. Runemasters are monk-like melee fighters who inscribe runes of power onto their flesh and weapons. As a Runemaster, you act as a Keeper of the Titans, and your journey will culminate in helping the Cenarion Circle fight against the Old God C'Thun.",

    ["Berserker_ROGUE"] = "Troll Berserkers are fearsome warriors who enter frenzied rages in battle, hacking through enemies with blades and daggers while hurling throwing weapons at distant foes. Trolls become Berserkers through a combination of learning how to channel their rage and alchemical means. Many Berserkers are addicted to strength elixirs and thistle brews. Throughout your journey as a Berserker, you will take revenge from the Bloodscalp, Skullsplitter, and Gurubashi Trolls for pushing the Darkspear Tribe out of Stranglethorn Vale.",

    ["Berserker_WARRIOR"] = "Troll Berserkers are fearsome warriors who enter frenzied rages in battle, hacking through enemies with axes while hurling throwing weapons at distant foes. Trolls become Berserkers through a combination of learning how to channel their rage and alchemical means. Many Berserkers are addicted to strength elixirs and rage potions. Throughout your journey as a Berserker, you will take revenge from the Bloodscalp, Skullsplitter, and Gurubashi Trolls for pushing the Darkspear Tribe out of Stranglethorn Vale.",

    ["Brave"] = "Braves are the frontline defenders of the Tauren people, warriors who have proven their courage through rites of passage on the open plains of Mulgore. Armed with polearms and wearing war harnesses instead of heavy plate, they embody the martial traditions of the Horde's most honorable race. A Brave fights not for glory but for the safety of the tribe, standing firm against quilboar, centaur, and any who threaten the grasslands. Throughout your journey as a Brave, you will take on increasingly difficult missions for your Chieftan to bring yourself honor amongst your people.",

    ["Tinker"] = "The Gnomes are a race of diminutive and highly intelligent humanoids, known for their mastery of technology. According to Muradin Bronzebeard, no gnome can turn down a puzzle. Hence, Gnomes are the Alliance's consummate tinkers. When a member of the Alliance thinks of a tinker, he thinks of a gnome; and when he thinks of a gnome, he thinks of a tinker. As a Tinker, you take your inventions into the field, deploying experimental gadgets in the heat of battle. Your journey will culminate in defeating Trade Master Kovic with his own mechanical companion.",

    ["Warden"] = "Wardens are the elite Night Elf jailers and hunters who once guarded Illidan Stormrage in his prison beneath Hyjal. When a prisoner escapes, the Wardens track them relentlessly across any distance. A Warden never abandons the hunt. They are master assassins who fight with poisoned daggers and thrown weapons. As a Warden, your journey will culminate in liberating the hidden Night Elven city of Shen'dralar from its crazed ruler.",

    ["Wilderness Stalker"] = "Wilderness Stalkers are Troll hunters who survive on instinct alone, drifting through the wild places of Azeroth with no permanent home. They favor thrown weapons and dual axes over bows, tracking prey through jungles and deserts alike. No one can match a Wilderness Stalker for their ability to survive in harsh environments. Wilderness Stalkers claim that the lands speak to them, aiding them in their hunting and protecting them. As a Wilderness Stalker, your journey will culminate in taming a Bloodaxe Worg in Blackrock Spire.",

    ["Lightslayer"] = "The Cult of Forgotten Shadows is a group considered heretical by most, which believes that dark energy practitioners are just as vital to the survival of life and reality as wielders of the Light. Lightslayers are a branch of the Cult of the Forgotten Shadow, trained to combat Scarlet Crusade raids. They are Forsaken shadow priests who have fully rejected the Holy Light that sustained them in life. Lightslayers embrace the void with fervor, wielding shadow magic and cursed daggers against the living and the Scarlet Crusade alike. As a Lightslayer, your journey will culminate in slaying the Scarlet Oracle.",

    ["Hedge Wizard"] = "Dalaran is one of the seven human kingdoms of Azeroth. It is ruled by the Kirin Tor, an elite cadre of the most powerful wizards in the known world. All Human, Gnome, and High Elven mages are trained in the magic schools of Dalaran where they study ancient tomes and practice arcane magic. However, Dalaran does not welcome other races. Hedge Wizards are self-taught mages who never attended the academies of Dalaran. They learn their craft through trial and error, folklore, and stolen scraps of arcane knowledge. As a Hedge Wizard, your journey will culminate in seeking Archmage Xylem & Lorekeeper Lydros to finally learn to Conjure Water and Polymorph.",

    ["Sister of Steel"] = "In this time of conflict, women perform the tasks traditionally reserved for men, such as working at the forge. The Sisters of Steel are just such a group of female blacksmiths. Long experience at the forge toughens the sisters' skin and strengthens their muscles to the point where they can plunge their hands into fire without wincing, and blades rebound from their flesh. When the need arises, the sisters of steel lift the weapons they forged and move out to combat their enemies. As a Sister of Steel, your journey will culminate in forging an epic hammer with the aid of The Mithril Order.",

    ["Dragonsworn"] = "For centuries, the great Dragonflights have noted the potential of younger races. In a few select cases, they choose a creature of another race to be one of a select few with the privilege of directly serving a dragon or an entire group of dragons. Such devotees dedicate their lives to the protection and service of their Dragonflights and reap the benefits of the great knowledge and power that their draconic masters share. Traditionally, the most well-known Dragonsworn are Night Elves in service of Ysera, the Aspect of the Green Dragonflight. Throughout your journey as a Dragonsworn, you will adopt a dragon companion and cleanse the Temple of Atal'Hakkar.",

    ["Kirin Tor Mage"] = "The Kirin Tor is an elite council of wizards who rule the legendary city of Dalaran. As the guardians of Azeroth’s premier academy of magic, they welcome promising mages from across Alliance lands. As an apprentice Kirin Tor Mage, you will learn how to conjure frost and fire using arcane magic. Throughout your journey as a Kirin Tor Mage, you will seek out, complete tasks for, and learn from powerful mages all across Azeroth.",

    ["Ley Walker"] = "The traditions of the Ley Walkers date back to the ancient time of the Titans, creators of runic magic and the imprisoners of Old Gods. Magicians known as Ley Walkers learn to sense and manipulate the runic magic eminating from the vast web of ley lines running beneath Azeroth's surface. As a Ley Walker, you act as a Keeper of the Titans, and your journey will culminate in helping the Cenarion Circle fight against the Old God C'Thun.",

    ["Gladiator"] = "Gladiators are combatants, slaves, or prisoners forced to fight in arenas or pits. Many of Azeroth's greatest heros were Gladiators during their enslavement, including Thrall and Varian Wrynn. Unaccustomed to civilized society or formal education, Gladiators usually speak only their native tongue. Throughout your journey as a Gladiator, you will take on increasingly challenging 'Wanted' jobs and act as a bounty hunter.",

    ["Dark Ranger"] = "During the Fall of Quel'Thalas, Prince Arthas Menethil raised the fallen members of Ranger-General Sylvanas Windrunner's army as Undead. These fallen High Elves would become known as Darkfallen, prowling the lands as Dark Rangers for the Scourge. Over time, some returned to the forests, others were sent on missions, and a few simply stayed put. When Arthas' power began to wane after his return from Kalimdor, Sylvanas called the Dark Rangers to her side, who then accompanied her to Deatholme to reclaim her body. Throughout your journey as a Dark Ranger, you will be tested on your ability to kite deadly enemies using your bow.",

    ["Druid of the Wild"] = "After the Legion's invasion, some Druids began to use the powers of all animal forms, combining their strengths against their enemies and becoming the Druids of the Wild. A Druid of the Wild divides their attention between combat ability and magical prowess. They harness nature and arcane magic to heal or harm, seamlessly shifting forms to absorb crushing blows or unleash devastating attacks. As a Druid of the Wild, your journey will culminate in safely containing the corrupted felvine in Dire Maul.",

    ["Shieldbearer"] = "Shieldbearers use holy magic to shield themselves and defend allies from attackers. With heavy armor, spikey shields, and an array of powerful defensive spells, Shieldbearers are often hard to defeat even without a healer by their side. Throughout your journey as a Shieldbearer, you will hone your ability to face and defeat big crowds of enemies.",

    ["Twilight Cultist"] = "Twilight's Hammer is a nihilist quasi-religious sect active across Azeroth that fanatically serves and worships the Old Gods and seeks to bring about the end of the world. Originally founded by Cho'gall as a Clan of Pale Orcs, the cult has been active since before the First War and recently became a major worldwide threat. As a Twilight Cultist, your journey will culminate in massacring the Druids of the Cenarion Circle who try to prevent the resurgence of the Old God C'Thun.",

}
